//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIFI.CS.Teil2.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texte {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texte() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WIFI.CS.Teil2.Properties.Texte", typeof(Texte).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Abbrechen {
            get {
                return ResourceManager.GetString("Abbrechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closes all windows but this ähnelt.
        /// </summary>
        public static string AndereFensterSchließenTipp {
            get {
                return ResourceManager.GetString("AndereFensterSchließenTipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WIFI Client / Server Application ähnelt.
        /// </summary>
        public static string AppTitel {
            get {
                return ResourceManager.GetString("AppTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Busy ähnelt.
        /// </summary>
        public static string Beschäftigt {
            get {
                return ResourceManager.GetString("Beschäftigt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting data... ähnelt.
        /// </summary>
        public static string DatenHolen {
            get {
                return ResourceManager.GetString("DatenHolen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date: ähnelt.
        /// </summary>
        public static string Datum {
            get {
                return ResourceManager.GetString("Datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string EinstellungsFensterName {
            get {
                return ResourceManager.GetString("EinstellungsFensterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open a new settings window ähnelt.
        /// </summary>
        public static string EinstellungsFensterTipp {
            get {
                return ResourceManager.GetString("EinstellungsFensterTipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fault ähnelt.
        /// </summary>
        public static string Fehler {
            get {
                return ResourceManager.GetString("Fehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All windows will be closed! Are you sure? ähnelt.
        /// </summary>
        public static string FensterSchließenFrage {
            get {
                return ResourceManager.GetString("FensterSchließenFrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closes all windows ähnelt.
        /// </summary>
        public static string FensterSchließenTipp {
            get {
                return ResourceManager.GetString("FensterSchließenTipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Country: ähnelt.
        /// </summary>
        public static string Landbeschreibung {
            get {
                return ResourceManager.GetString("Landbeschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opens a new window (Ctrl + N) ähnelt.
        /// </summary>
        public static string NeuesFensterTipp {
            get {
                return ResourceManager.GetString("NeuesFensterTipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        public static string Sprache {
            get {
                return ResourceManager.GetString("Sprache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart the application to use the new language! ähnelt.
        /// </summary>
        public static string SprachenNeustart {
            get {
                return ResourceManager.GetString("SprachenNeustart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the language to be used from the next session onward ähnelt.
        /// </summary>
        public static string SprachenTipp {
            get {
                return ResourceManager.GetString("SprachenTipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run ähnelt.
        /// </summary>
        public static string Starten {
            get {
                return ResourceManager.GetString("Starten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Demonstrates how to abort a running thread using TAP ähnelt.
        /// </summary>
        public static string TAPInfo {
            get {
                return ResourceManager.GetString("TAPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deactivates dark design ähnelt.
        /// </summary>
        public static string ThemenWechselDark {
            get {
                return ResourceManager.GetString("ThemenWechselDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activates dark design ähnelt.
        /// </summary>
        public static string ThemenWechselHell {
            get {
                return ResourceManager.GetString("ThemenWechselHell", resourceCulture);
            }
        }
    }
}
